site_name: React Auth Kit
site_description: Authentication Library for React Js for Token Based Auth using Json Web Token(JWT)
site_author: Arkadip Bhattacharya
site_url: https://authkit.arkadip.me

repo_url: https://github.com/react-auth-kit/react-auth-kit
repo_name: react-auth-kit/react-auth-kit

copyright:  Copyright &copy; 2020 - 2021 React Auth Kit

theme:
  name: 'material'
  custom_dir: docs/docs_overrides/
  icon:
    repo: fontawesome/brands/github
  logo: img/logo.svg
  favicon: img/favicon.png

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Integrate in your project: 'integration.md'
  - Sign In: 'signin.md'
  - Private Route: 'privateroute.md'
  - Sign Out: 'signout.md'
  - Auth User Data: 'authdata.md'
  - Auth Header: 'authheader.md'
  - Check Authentication: 'checkauth.md'
  - Refresh Token: 'refreshtoken.md'
  - Contributing: 'contributing.md'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
