on:
  release:
    types:
      - published

name: Release

jobs:
  release-docs:
    name: Release Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Tag viewing
        run: echo ${{ github.event.release.tag_name }}

      - name: Install dependency
        run: pip install mkdocs-material

      - name: Deploying docs
        run: mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
